# -*- coding: utf-8 -*-
"""foobarQ1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qcufeymW2yT9oEyR1xN134SgIie8AMFd
"""

def primeString(n,m):
    string = ""
    for num in range(n, m+1):
        if num > 1:
            for i in range(2, num):
                if(num % i) == 0:
                    break
            else:
                if len(string) <= 10005:
                    string = string + str(num)


    return string

def solution(i):
    if i < 0 & i > 10000:
        quit()
    else:
        print(string[i:i+5])


string = primeString(1,20250)

