# -*- coding: utf-8 -*-
"""FoobarQ4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1shoUsysMuYrutQaNG62FoX_wIMueEXp-
"""

def solution(n):
  m = [[0 for i in range(n + 1)] for j in range(n + 1)]
  m[0][0] = 1
  for s in range(1, n + 1):
    for l in range(0, n +1):
      m[s][l] = m[s - 1][l]
      if l >= s:
        m[s][l] = m[s][l] + m[s - 1][l - s]
  return m[n][n] - 1

solution(5)