# -*- coding: utf-8 -*-
"""FoobarQ5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mbryKsuo6e7VFRXDKxLWw9Pxwwh8ZeCb
"""

def check(n):
  val = n % 4
  if val == 0:
    return n
  if val == 1:
    return 1
  if val == 2:
    return n + 1
  return 0

def solution(start, length):
  if length == 1:
    return start
  val = check(start + 2*(length - 1))
  if start > 1:
    val = val ^ check(start - 1)
  for i in range(length - 2):
    cha = length - 2 - i
    init = start + length*(2 + i) - 1
    val = val ^ check(init + cha) ^ check(init)

  return val

solution(17, 4)