# -*- coding: utf-8 -*-
"""FoobarQ6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19S0lgSEXxeLpd7qroFsvUGIkoknYl6L2
"""

def solution(n):
  n = int(n)
  residue = 0

  while(n!=1):
    if (n%2==0):
      n = n/2
    elif((n == 3) or ((n + 1) & n) > ((n - 1) & (n - 2))):
      n-=1
    else:
      n+=1
    residue+=1
  return residue

solution('4')