# -*- coding: utf-8 -*-
"""foobarQ2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVPEsWf3ndW6Lqa1zP2BADtXwkUp2hkO
"""

def get_index(h, inde):
  max_inde = 2**h - 1
  if max_inde < inde:
    return -1
  else:
    node_offset = 0
    continue_ahead = True
    subtree_size = max_inde
    result = -1

    while continue_ahead:
      if subtree_size == 0:
        continue_ahead = False

      subtree_size = subtree_size >> 1

      left_node = node_offset + subtree_size

      right_node = left_node + subtree_size

      my_node = right_node + 1

      if(left_node == inde) | (right_node == inde):
        result = my_node
        continue_ahead = False

      if(inde > left_node):
        node_offset = left_node

    return result

def solution(h, q):
  return [get_index(h, x) for x in q ]

solution(5,[19,14, 28])